CREATE TYPE IF NOT EXISTS "JobStatus" AS ENUM ('DRAFT','OPEN','CLOSED');
CREATE TYPE IF NOT EXISTS "JobUrgency" AS ENUM ('LOW','MEDIUM','HIGH');
CREATE TYPE IF NOT EXISTS "JobWorkMode" AS ENUM ('ON_SITE','REMOTE','BOTH');
CREATE TYPE IF NOT EXISTS "UserRole" AS ENUM ('ADMIN','CLIENT','PROFESSIONAL');
CREATE TYPE IF NOT EXISTS "CmsPageStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
